import nodemailer from "nodemailer";

export async function POST(req) {
  try {
    const { firstName, email, phone, message } = await req.json();

    // Create transporter using Gmail or your SMTP
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const mailOptions = {
      from: email,
      to: "mojaealestate1@gmail.com",
      subject: `New Contact Message from ${firstName}`,
      html: `
<div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333333; max-width: 600px; margin: 20px auto; border: 1px solid #dddddd; padding: 0;">
    <div style="background-color: #002244; color: white; padding: 20px; text-align: center;">
        <h1 style="margin: 0; font-size: 24px;">NEW LEAD: Moja Realestate Contact Form</h1>
    </div>

    <div style="padding: 30px;">
        <p style="font-size: 16px;">
            A new contact form submission has been received from the Moja Realestate website.
            Please follow up promptly.
        </p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr style="background-color: #f4f4f4;">
                <td style="padding: 10px; border: 1px solid #dddddd; width: 30%;"><strong>Name:</strong></td>
                <td style="padding: 10px; border: 1px solid #dddddd;">${firstName}</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #dddddd; width: 30%;"><strong>Email:</strong></td>
                <td style="padding: 10px; border: 1px solid #dddddd;"><a href="mailto:${email}" style="color: #002244; text-decoration: none;">${email}</a></td>
            </tr>
            <tr style="background-color: #f4f4f4;">
                <td style="padding: 10px; border: 1px solid #dddddd; width: 30%;"><strong>Phone:</strong></td>
                <td style="padding: 10px; border: 1px solid #dddddd;">${
                  phone || "N/A"
                }</td>
            </tr>
        </table>

        <h3 style="margin-top: 30px; color: #002244; border-bottom: 2px solid #DDAC4F; padding-bottom: 5px;">Client Message:</h3>
        <div style="background-color: #ffffff; border: 1px solid #cccccc; padding: 15px; white-space: pre-wrap; margin-bottom: 20px;">
            <p style="margin: 0;">${message}</p>
        </div>
        
        <div style="text-align: center; margin-top: 25px;">
            <a href="mailto:${email}" style="display: inline-block; padding: 10px 20px; background-color: #DDAC4F; color: #002244; text-decoration: none; border-radius: 5px; font-weight: bold;">
                REPLY TO LEAD
            </a>
        </div>

    </div>

    <div style="background-color: #eeeeee; color: #777777; padding: 15px; text-align: center; font-size: 12px; border-top: 1px solid #dddddd;">
        This email was automatically generated by the Moja Realestate contact system.
    </div>
</div>
`,
    };

    await transporter.sendMail(mailOptions);

    return new Response(
      JSON.stringify({ success: true, message: "Email sent!" }),
      { status: 200 }
    );
  } catch (error) {
    console.log("Email error:", error);
    return new Response(
      JSON.stringify({ success: false, message: "Failed to send email." }),
      { status: 500 }
    );
  }
}
