import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "./component/Footer";
// import WhatsAppFloat from "./component/WhatsAppFloat"; // Import the component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moja Real Estate",
  description: "Generated by Moja Real Estate",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <Navbar />

        {children}

        {/* WhatsApp Button acts as an overlay */}
        {/* <WhatsAppFloat /> */}

        <Footer />
      </body>
    </html>
  );
}
